version: "3.10"

services:
  app:
    build: .
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8029:8029"
    command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn core.wsgi:application -w 4 -b 0.0.0.0:8029"
    env_file:
      - .env
 # На самом деле этот сервис не нужен, так как SQLite не требует отдельного контейнера

#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - "80:80"
#    depends_on:
#      - app
