# Generated by Django 5.1 on 2024-08-21 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='about_us/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название преимущества')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название преимущества')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название преимущества')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Название преимущества')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advantages/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название здания')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название здания')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название здания')),
                ('name_ky', models.CharField(max_length=200, null=True, verbose_name='Название здания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='buildings/', verbose_name='Изображение')),
                ('file', models.FileField(upload_to='buildings/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('address_en', models.TextField(null=True, verbose_name='Адрес')),
                ('address_ru', models.TextField(null=True, verbose_name='Адрес')),
                ('address_ky', models.TextField(null=True, verbose_name='Адрес')),
                ('map', models.TextField(blank=True, null=True, verbose_name='Карта')),
                ('map_en', models.TextField(blank=True, null=True, verbose_name='Карта')),
                ('map_ru', models.TextField(blank=True, null=True, verbose_name='Карта')),
                ('map_ky', models.TextField(blank=True, null=True, verbose_name='Карта')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название застройщика')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название застройщика')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название застройщика')),
                ('name_ky', models.CharField(max_length=200, null=True, verbose_name='Название застройщика')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='developers/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Застройщик',
                'verbose_name_plural': 'Застройщики',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('name_ky', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('message_en', models.TextField(null=True, verbose_name='Сообщение')),
                ('message_ru', models.TextField(null=True, verbose_name='Сообщение')),
                ('message_ky', models.TextField(null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
        migrations.CreateModel(
            name='MainBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Подзаголовок')),
                ('subtitle_en', models.CharField(max_length=200, null=True, verbose_name='Подзаголовок')),
                ('subtitle_ru', models.CharField(max_length=200, null=True, verbose_name='Подзаголовок')),
                ('subtitle_ky', models.CharField(max_length=200, null=True, verbose_name='Подзаголовок')),
                ('first_text_title', models.CharField(max_length=200, verbose_name='Заголовок первого текста')),
                ('first_text_title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок первого текста')),
                ('first_text_title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок первого текста')),
                ('first_text_title_ky', models.CharField(max_length=200, null=True, verbose_name='Заголовок первого текста')),
                ('first_text', models.TextField(verbose_name='Первый текст')),
                ('first_text_en', models.TextField(null=True, verbose_name='Первый текст')),
                ('first_text_ru', models.TextField(null=True, verbose_name='Первый текст')),
                ('first_text_ky', models.TextField(null=True, verbose_name='Первый текст')),
                ('second_text_title', models.CharField(max_length=200, verbose_name='Заголовок второго текста')),
                ('second_text_title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок второго текста')),
                ('second_text_title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок второго текста')),
                ('second_text_title_ky', models.CharField(max_length=200, null=True, verbose_name='Заголовок второго текста')),
                ('second_text', models.TextField(verbose_name='Второй текст')),
                ('second_text_en', models.TextField(null=True, verbose_name='Второй текст')),
                ('second_text_ru', models.TextField(null=True, verbose_name='Второй текст')),
                ('second_text_ky', models.TextField(null=True, verbose_name='Второй текст')),
            ],
            options={
                'verbose_name': 'Блок главной страницы',
                'verbose_name_plural': 'Блоки главной страницы',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название услуги')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название услуги')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Название услуги')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdvantageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название преимущества')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название преимущества')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название преимущества')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Название преимущества')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('advantages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='cms.advantages', verbose_name='Преимущество')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название услуги')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название услуги')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.FileField(upload_to='services/', verbose_name='Изображение')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='cms.services', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
