# Generated by Django 5.1 on 2024-08-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(null=True, upload_to='about_us/', verbose_name='Изображение'),
        ),
    ]
