# Generated by Django 5.1 on 2024-10-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [

        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('site_description', models.TextField(verbose_name='Описание сайта')),
                ('site_logo', models.FileField(blank=True, null=True, upload_to='site_logos', verbose_name='Логотип сайта')),
                ('site_bottom_logo', models.FileField(blank=True, null=True, upload_to='site_logos', verbose_name='Логотип нижней части сайта')),
                ('site_favicon', models.FileField(blank=True, null=True, upload_to='site_favicons', verbose_name='Иконка сайта')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета описание')),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='images/meta', verbose_name='Мета изображение')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),

    ]
