# Generated by Django 5.1 on 2024-08-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [

        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_zh_hans',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='advantageitem',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='advantageitem',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='advantageitem',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='advantageitem',
            name='description_zh_hans',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='advantageitem',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Название преимущества'),
        ),
        migrations.AddField(
            model_name='advantageitem',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название преимущества'),
        ),
        migrations.AddField(
            model_name='advantageitem',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Название преимущества'),
        ),
        migrations.AddField(
            model_name='advantageitem',
            name='title_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='Название преимущества'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Название преимущества'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название преимущества'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Название преимущества'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='title_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='Название преимущества'),
        ),
        migrations.AddField(
            model_name='building',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='building',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='building',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='building',
            name='description_zh_hans',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='building',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Название здания'),
        ),
        migrations.AddField(
            model_name='building',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название здания'),
        ),
        migrations.AddField(
            model_name='building',
            name='name_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Название здания'),
        ),
        migrations.AddField(
            model_name='building',
            name='name_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='Название здания'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_text_ar',
            field=models.TextField(null=True, verbose_name='Текст для телефонов'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_text_en',
            field=models.TextField(null=True, verbose_name='Текст для телефонов'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_text_tr',
            field=models.TextField(null=True, verbose_name='Текст для телефонов'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_text_zh_hans',
            field=models.TextField(null=True, verbose_name='Текст для телефонов'),
        ),
        migrations.AddField(
            model_name='contact',
            name='small_text_ar',
            field=models.TextField(null=True, verbose_name='Короткий текст'),
        ),
        migrations.AddField(
            model_name='contact',
            name='small_text_en',
            field=models.TextField(null=True, verbose_name='Короткий текст'),
        ),
        migrations.AddField(
            model_name='contact',
            name='small_text_tr',
            field=models.TextField(null=True, verbose_name='Короткий текст'),
        ),
        migrations.AddField(
            model_name='contact',
            name='small_text_zh_hans',
            field=models.TextField(null=True, verbose_name='Короткий текст'),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_ar',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_tr',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_zh_hans',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='developer',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='developer',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='developer',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='developer',
            name='description_zh_hans',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='developer',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Название застройщика'),
        ),
        migrations.AddField(
            model_name='developer',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название застройщика'),
        ),
        migrations.AddField(
            model_name='developer',
            name='name_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Название застройщика'),
        ),
        migrations.AddField(
            model_name='developer',
            name='name_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='Название застройщика'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='message_ar',
            field=models.TextField(null=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='message_en',
            field=models.TextField(null=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='message_tr',
            field=models.TextField(null=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='message_zh_hans',
            field=models.TextField(null=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='name_zh_hans',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='first_text_ar',
            field=models.TextField(null=True, verbose_name='Первый текст'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='first_text_en',
            field=models.TextField(null=True, verbose_name='Первый текст'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='first_text_title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок первого текста'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='first_text_title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок первого текста'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='first_text_title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок первого текста'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='first_text_title_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок первого текста'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='first_text_tr',
            field=models.TextField(null=True, verbose_name='Первый текст'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='first_text_zh_hans',
            field=models.TextField(null=True, verbose_name='Первый текст'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='second_text_ar',
            field=models.TextField(null=True, verbose_name='Второй текст'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='second_text_en',
            field=models.TextField(null=True, verbose_name='Второй текст'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='second_text_title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок второго текста'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='second_text_title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок второго текста'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='second_text_title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок второго текста'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='second_text_title_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок второго текста'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='second_text_tr',
            field=models.TextField(null=True, verbose_name='Второй текст'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='second_text_zh_hans',
            field=models.TextField(null=True, verbose_name='Второй текст'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='subtitle_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='subtitle_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='subtitle_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='subtitle_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='mainblock',
            name='title_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='description_zh_hans',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='title_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='Название услуги'),
        ),
    ]
