# Generated by Django 5.1 on 2024-08-21 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_aboutus_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='developer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='cms.developer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='file',
            field=models.FileField(null=True, upload_to='buildings/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='building',
            name='image',
            field=models.ImageField(null=True, upload_to='buildings/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='logo',
            field=models.ImageField(null=True, upload_to='developers/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='image',
            field=models.FileField(null=True, upload_to='services/', verbose_name='Изображение'),
        ),
    ]
