# Generated by Django 5.1 on 2024-08-21 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_building_developer_alter_building_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='cms.developer'),
        ),
    ]
